# Generated by Django 4.2.3 on 2023-08-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="name",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
