# Generated by Django 4.2.4 on 2023-09-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0002_report_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
