# Generated by Django 4.2.3 on 2023-08-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=100)),
                ("details", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
            ],
        ),
    ]
