# Generated by Django 4.2.4 on 2023-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_cv"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CV",
        ),
        migrations.AddField(
            model_name="user",
            name="cv",
            field=models.FileField(default=None, null=True, upload_to="cv_files/"),
        ),
    ]
