# Generated by Django 4.2.4 on 2023-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_delete_cv_user_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fname",
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="lname",
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
