# Generated by Django 4.2.4 on 2023-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_user_address_user_com_name_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
