# Generated by Django 4.2.4 on 2023-09-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="high_score",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_score",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="secondary_score",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=4, null=True
            ),
        ),
    ]
