# Generated by Django 4.2.4 on 2023-09-21 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_user_high_score_user_primary_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="high_education",
            new_name="higherEducation",
        ),
    ]
