# Generated by Django 4.2.4 on 2023-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_rename_high_education_user_highereducation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="higherEducation",
            field=models.TextField(default="", max_length=200),
        ),
    ]
