# Generated by Django 4.2.4 on 2023-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_user_highereducation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="com_name",
            new_name="company_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="job_desc",
            new_name="job_description",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="pri_education",
            new_name="primaryEducation",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="sec_education",
            new_name="secondaryEducation",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="yoe",
            new_name="years_of_experience",
        ),
        migrations.AlterField(
            model_name="user",
            name="higherEducation",
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
