# Generated by Django 4.2.4 on 2023-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_rename_com_name_user_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="higherEducation",
            field=models.TextField(default="", max_length=200, null=True),
        ),
    ]
