# Generated by Django 4.2.4 on 2023-09-21 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_user_highereducation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="higherEducation",
            new_name="higher_education",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="primaryEducation",
            new_name="primary_education",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="secondaryEducation",
            new_name="secondary_education",
        ),
    ]
