# Generated by Django 4.2.4 on 2023-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_rename_highereducation_user_higher_education_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="company_name",
            new_name="com_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="job_description",
            new_name="high_education",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="primary_education",
            new_name="job_desc",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="secondary_education",
            new_name="pri_education",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="years_of_experience",
            new_name="sec_education",
        ),
        migrations.RemoveField(
            model_name="user",
            name="higher_education",
        ),
        migrations.AddField(
            model_name="user",
            name="yoe",
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
