# Generated by Django 4.2.4 on 2023-09-21 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_rename_company_name_user_com_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="high_education",
            new_name="higher_education",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="pri_education",
            new_name="primary_education",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="sec_education",
            new_name="secondary_education",
        ),
    ]
