# Generated by Django 4.2.4 on 2023-09-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_rename_high_education_user_higher_education_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="com_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="high_score",
        ),
        migrations.RemoveField(
            model_name="user",
            name="higher_education",
        ),
        migrations.RemoveField(
            model_name="user",
            name="job_desc",
        ),
        migrations.RemoveField(
            model_name="user",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="primary_education",
        ),
        migrations.RemoveField(
            model_name="user",
            name="primary_score",
        ),
        migrations.RemoveField(
            model_name="user",
            name="secondary_education",
        ),
        migrations.RemoveField(
            model_name="user",
            name="secondary_score",
        ),
        migrations.RemoveField(
            model_name="user",
            name="yoe",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
