# Generated by Django 4.2.4 on 2023-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_predictiveindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictiveindex",
            name="lname",
            field=models.TextField(default=None, max_length=100),
        ),
    ]
