# Generated by Django 4.2.4 on 2023-09-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0021_predictiveindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictiveindex",
            name="checkbox1_pi",
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="predictiveindex",
            name="checkbox2_pi",
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="predictiveindex",
            name="checkbox3_pi",
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="predictiveindex",
            name="radio11",
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="predictiveindex",
            name="radio12",
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="predictiveindex",
            name="radio13",
            field=models.TextField(default=None, max_length=100),
        ),
    ]
