# forms.py
from django import forms

class CVUploadForm(forms.Form):
    cv = forms.FileField()
    fname = forms.CharField(max_length=255)
    lname = forms.CharField(max_length=255)
    email = forms.EmailField()
    phone = forms.IntegerField()
    address = forms.CharField(max_length=200)
    gender = forms.CharField(max_length=6)
    primary_education = forms.CharField(max_length=200)
    secondary_education = forms.CharField(max_length=200)
    higher_education = forms.CharField(max_length=200)
    job_title = forms.CharField(max_length=200)
    yoe = forms.CharField(max_length=200)
    com_name = forms.CharField(max_length=200)
    job_desc = forms.CharField(max_length=200)
    primary_score = forms.DecimalField(decimal_places=2, max_digits=4)
    secondary_score = forms.DecimalField(decimal_places=2, max_digits=4)
    high_score = forms.DecimalField(decimal_places=2, max_digits=4)

class PredictiveIndex(forms.Form):
    language = forms.CharField()
    fname = forms.TextInput()
    mname = forms.TextInput()
    lname = forms.TextInput()
    email = forms.TextInput()
    pi_id = forms.TextInput()
    age = forms.TextInput()
    gender = forms.TextInput()
    race = forms.TextInput()
    education = forms.TextInput()
    radio11 = forms.TextInput()
    radio12 = forms.TextInput()
    radio13 = forms.TextInput()
    checkbox1_pi = forms.TextInput()
    checkbox2_pi = forms.TextInput()
    checkbox3_pi = forms.TextInput()
