# models.py
from django.db import models

class User(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    cv = models.FileField(upload_to='cv_files/', default=None, null=True) 
    fname = models.TextField(max_length=200, default=None, null=True)
    lname = models.TextField(max_length=200, default=None, null=True)
    email = models.EmailField(default=None, null=True)
    phone = models.IntegerField(default=None, null=True)
    address = models.TextField(max_length=200, default=None, null=True)
    gender = models.TextField(max_length=6, null=True, default=None)
    primary_education = models.TextField(max_length=200, default=None, null=True)
    secondary_education = models.TextField(max_length=200, default=None, null=True)
    higher_education = models.TextField(max_length=200, default=None, null=True)
    job_title = models.TextField(max_length=200, default=None, null=True)
    yoe = models.TextField(max_length=200, default=None, null=True)
    com_name = models.TextField(max_length=200, default=None, null=True)
    job_desc = models.TextField(max_length=200, default=None, null=True)
    primary_score = models.DecimalField(decimal_places=2 , max_digits=4, default=None, null=True)
    secondary_score = models.DecimalField(decimal_places=2, max_digits=4, default=None, null=True)
    high_score = models.DecimalField(decimal_places=2, max_digits=4, default=None, null=True)

class PredictiveIndex(models.Model):
    language = models.CharField(max_length=100)
    fname = models.TextField(max_length=100)
    mname = models.TextField(max_length=100)
    lname = models.TextField(max_length=100, default=None)
    email = models.TextField(max_length=100)
    pi_id = models.TextField(max_length=100)
    age = models.TextField(max_length=100)
    gender = models.TextField(max_length=100)
    race = models.TextField(max_length=100)
    education = models.TextField(max_length=100)
    radio11 = models.TextField(max_length=100, default=None)
    radio12 = models.TextField(max_length=100, default=None)
    radio13 = models.TextField(max_length=100, default=None)
    checkbox1_pi = models.TextField(max_length=100, default=None)
    checkbox2_pi = models.TextField(max_length=100, default=None)
    checkbox3_pi = models.TextField(max_length=100, default=None)